### ISSUE TITLE
adding pip to environemnt file

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/ruspy#10]
conda env update -f environment.yml 
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

**Comment by MaxBlesch** [comment]
Done
