### ISSUE TITLE
separating the decision from the simulation

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/ruspy#16]
I want us to split `simulate` explicitly in `get_decision` and `simulation` of experience given the decision rule ... this seems useful for us now as in our case the probabilities determining both are not the same

**Comment by MaxBlesch** [comment]
Maybe we discuss this next week?

**Comment by peisenha** [comment]
Yes, please put on ASANA so we do not forget.

**Comment by peisenha** [comment]
We will revisit this once we get to the major refactoring for your thesis.
